defaults: &defaults
  sms:
    template_code:
      verify_code: <%= ENV['SETTING_TEMPLATE_CODE_VERIFY_CODE'] %>
      reservation: <%= ENV['SETTING_TEMPLATE_CODE_RESERVATION'] %>
      reservation_for_admin: <%= ENV['SETTING_TEMPLATE_CODE_RESERVATION_FOR_ADMIN'] %>
    sign_name: <%= ENV['SETTING_SIGN_NAME'] %>
  aliyun:
    access_key_id: <%= ENV['SETTING_ALIYUN_ACCESS_KEY_ID'] %>
    access_key_secret: <%= ENV['SETTING_ALIYUN_ACCESS_KEY_SECRET'] %>
  juhe:
    app_key: <%= ENV['SETTING_JUHE_APP_KEY'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
